# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
  # Set options, as documented at https://datatables.net/reference/option/
  options:
    lengthMenu: [10, 25, 50, 100, 250, 500, 1000, 2500]
    pageLength: 50
    dom: f<<'content-wrapper__select'l>>tr<<'pagination'p >>,
    pagingType: simple_numbers

  template: 'datatable_html.html.twig'

  template_parameters:
    # Example classes to integrate nicely with Bootstrap 3.x
#    className: 'table'

#  renderer:             Omines\DataTablesBundle\Twig\TwigRenderer

  # You can for example override this to "tables" to keep the translation domains separated nicely
  translation_domain: 'messages'
