<?php

namespace App\Services\EntityActions\Editor;

use App\Services\EntityActions\AbstractEntityActionsService;
use Exception;

/**
 * Class AbstractEditService
 * @package App\Services\EntityActions\Editor
 */
abstract class AbstractEditorService extends AbstractEntityActionsService
{
    /**
     * AbstractEditorService constructor.
     * @param string $entityClass
     */
    public function __construct(string $entityClass)
    {
        $this->entityClass = $entityClass;
    }

    /**
     * @param array $options
     * @param null $entity
     * @throws Exception
     */
    public function before(array $options = [], $entity = null): void
    {
        parent::before($options, $entity); // TODO: Change the autogenerated stub
        $this->setEntity($entity);
    }
}