parameters:
# Параметры компании
  project_info:
    site_name: 'Медицина'
    address_line_1: 'ул. Ленина д.30'
    address_line_2: 'Курск, Россия'
# Пользователь Система
  system_user_phone: '9999999999'
