parameters:
# Параметры почты
  email_parameters:
    account_name: '%env(string:ACCOUNT_NAME)%'
    account_password: '%env(string:ACCOUNT_PASSWORD)%'
    smtp_host: '%env(string:SMTP_HOST)%'
    smtp_port: '%env(int:SMTP_PORT)%'
    smtp_encryption: 'ssl'
# Параметры компании
  sms_parameters:
    sender: '3303'
    user: '%env(string:SMS_BEELINE_USER)%'
    password: '%env(string:SMS_BEELINE_PASSWORD)%'
# Параметры компании
  project_info:
    site_name: 'Медицина'
    address_line_1: 'ул. Ленина д.30'
    address_line_2: 'Курск, Россия'
# Статусы СМС
  sms_statuses:
    delivered: 'delivered'
    not_delivered: 'not_delivered'
    wait: 'wait'
    failed: 'failed'
# Время обновления смс
  sms_update_times:
    period_to_update: 25
    period_to_check: 2
# Параметры номеров
  phone_parameters:
    phone_prefix_ru: '+7'
# Параметры номеров
  time_formats:
    besms: 'd.m.Y H:i:s'
# Пользователь Система
  system_user_phone: '9999999999'
