parameters:
  staff_option: 'staff'
  prescription_option: 'prescription'
  medical_history_option: 'medicalHistory'
  prescription_medicine: 'prescriptionMedicine'
  patient_testing_option: 'patientTesting'
